
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/mibCommerce
    username: root
    password: imtheDANGER@218
  application:
    name: mibCommerce
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true
  data:
    redis:
      host: localhost
      port: 6380

cors:
  allowed-origins: http://localhost:3000