version: '3.8'

services:
  mibCommerce-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'imtheDANGER@218'
    ports:
      - "3305:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - mysql-data:/var/lib/mysql

  mibCommerce-redis:
    image: "redis:latest"
    container_name: "mibCom-redis-container"
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mysql-data: